import type { ServiceCategory } from './types';

export const serviceCategories: ServiceCategory[] = [
  {
    id: 'painting',
    title: 'Painting Services',
    services: [
      {
        title: 'Living Room Wall Painting',
        description: 'Transform your living space with our professional wall painting services. Our expert painters deliver flawless finishes with premium paints, creating a warm and inviting atmosphere that reflects your personal style.',
        image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80',
        checklist: [
          'Free site visit & measurement',
          'Color consultation with expert',
          'Surface cleaning & preparation',
          'Crack filling & wall putty',
          'Primer application (2 coats)',
          'Premium paint application (2-3 coats)',
          'Edge cutting & detailing',
          'Final inspection & touch-ups',
          'Complete cleanup after work',
        ],
      },
      {
        title: 'Bedroom Wall Painting',
        description: 'Create your perfect bedroom sanctuary with our professional painting services. We help you choose calming colors and deliver a polished finish that ensures peaceful nights and beautiful mornings.',
        image: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=600&q=80',
        checklist: [
          'Free consultation & estimate',
          'Personalized color selection',
          'Furniture protection & covering',
          'Wall surface preparation',
          'Putty work for smooth finish',
          'Primer coat application',
          'Premium emulsion painting',
          'Accent wall design (if needed)',
          'Post-work cleaning',
        ],
      },
      {
        title: 'Exterior Wall Painting',
        description: 'Protect and beautify your property with our exterior painting services. We use weather-resistant paints that shield against harsh sun, rain, and pollution while giving your home stunning curb appeal.',
        image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&q=80',
        checklist: [
          'Detailed exterior inspection',
          'Pressure washing & cleaning',
          'Crack & damage repair',
          'Waterproofing treatment',
          'Weather-resistant primer',
          'Exterior grade paint (3 coats)',
          'Window & door frame painting',
          'Boundary wall painting',
          'Quality inspection & warranty',
        ],
      },
      {
        title: 'Interior Wall Painting',
        description: 'Complete interior painting solutions for homes and offices. Our skilled painters transform your spaces with vibrant colors and smooth finishes using high-quality Asian Paints products.',
        image: 'https://images.unsplash.com/photo-1562663474-6cbb3eaa4d14?w=600&q=80',
        checklist: [
          'Room-by-room assessment',
          'Complete color planning',
          'All furniture covering',
          'Old paint scraping (if needed)',
          'Wall putty & leveling',
          'Primer application',
          'Premium interior paint',
          'Ceiling painting included',
          'Switch board area finishing',
          'Full site cleanup',
        ],
      },
      {
        title: 'Kitchen Wall Painting',
        description: 'Specialized kitchen painting with moisture and stain-resistant finishes. We use semi-gloss and satin paints that are easy to clean and maintain, perfect for high-humidity areas.',
        image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80',
        checklist: [
          'Kitchen-specific assessment',
          'Grease & stain removal',
          'Anti-fungal treatment',
          'Moisture-resistant primer',
          'Washable paint application',
          'Cabinet exterior painting',
          'Backsplash area finishing',
          'Oil & heat resistant coating',
          'Easy-clean surface finish',
        ],
      },
      {
        title: 'Bathroom Wall Painting',
        description: 'Moisture-proof bathroom painting solutions that prevent mold and mildew. Our specialized paints create a clean, fresh look while protecting against humidity damage.',
        image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&q=80',
        checklist: [
          'Moisture damage assessment',
          'Mold & mildew treatment',
          'Waterproofing application',
          'Anti-fungal primer',
          'Bathroom-grade paint',
          'Ceiling waterproofing',
          'Pipe area sealing',
          'Ventilation check',
          'Long-lasting finish guarantee',
        ],
      },
      {
        title: 'Dining Room Wall Painting',
        description: 'Create an inviting dining atmosphere with our professional painting services. We help you choose warm, appetizing colors that make every meal a special occasion.',
        image: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600&q=80',
        checklist: [
          'Space evaluation',
          'Dining-appropriate colors',
          'Furniture protection',
          'Wall preparation work',
          'Premium paint selection',
          'Accent wall options',
          'Decorative finishes',
          'Clean edges & corners',
          'Post-painting cleanup',
        ],
      },
      {
        title: 'Wood Painting & Polish',
        description: 'Expert wood finishing services for furniture, doors, windows, and cabinets. We provide both paint and polish options to enhance the beauty and durability of your wooden surfaces.',
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
        checklist: [
          'Wood condition assessment',
          'Sanding & smoothing',
          'Dent & scratch repair',
          'Wood primer application',
          'Enamel paint / Polish',
          'Multiple coat finishing',
          'Hardware protection',
          'Grain enhancement (polish)',
          'Protective top coat',
        ],
      },
      {
        title: 'Metal Painting',
        description: 'Rust-proof metal painting for gates, grills, railings, and industrial surfaces. Our specialized metal paints provide long-lasting protection against corrosion and weather damage.',
        image: 'https://images.unsplash.com/photo-1558618047-f4b511aec194?w=600&q=80',
        checklist: [
          'Rust & corrosion check',
          'Surface cleaning & prep',
          'Rust removal treatment',
          'Anti-rust primer',
          'Metal-grade enamel paint',
          'Multiple protective coats',
          'Welding point coverage',
          'UV-resistant finish',
          'Long-term rust protection',
        ],
      },
    ],
  },
  {
    id: 'texture',
    title: 'Texture & Design Work',
    services: [
      {
        title: 'Texture Wall Painting',
        description: 'Add depth and character to your walls with our texture painting services. From subtle patterns to bold designs, we create stunning visual effects that make your walls stand out.',
        image: 'https://images.unsplash.com/photo-1615529328331-f8917597711f?w=600&q=80',
        checklist: [
          'Design consultation',
          'Texture pattern selection',
          'Wall surface preparation',
          'Base coat application',
          'Texture material mixing',
          'Pattern application',
          'Color layering',
          'Finishing touches',
          'Protective top coat',
        ],
      },
      {
        title: 'Stencil & Pattern Design',
        description: 'Custom stencil work and pattern designs for feature walls. Our artists create unique geometric, floral, or custom patterns that add personality to any room.',
        image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&q=80',
        checklist: [
          'Custom design planning',
          'Pattern mock-up approval',
          'Wall preparation',
          'Base color application',
          'Stencil placement',
          'Precise pattern painting',
          'Detail work & edges',
          'Color blending',
          'Final finishing',
        ],
      },
    ],
  },
  {
    id: 'interior-designers',
    title: 'Interior Design Services',
    services: [
      {
        title: '3D Interior Design',
        description: 'Visualize your dream space before execution with our 3D interior design services. We create realistic renderings to help you see exactly how your painted and designed space will look.',
        image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&q=80',
        checklist: [
          'Initial consultation',
          'Space measurement',
          'Requirement gathering',
          '3D model creation',
          'Color scheme planning',
          'Virtual walkthrough',
          'Revision & changes',
          'Final design approval',
          'Execution guidance',
        ],
      },
      {
        title: 'Color Consultation',
        description: 'Expert color consultation to help you choose the perfect shades for your home. Our designers consider lighting, furniture, and your preferences to create harmonious color schemes.',
        image: 'https://images.unsplash.com/photo-1615529328331-f8917597711f?w=600&q=80',
        checklist: [
          'Home visit & assessment',
          'Lighting analysis',
          'Existing decor review',
          'Color psychology guidance',
          'Shade card selection',
          'Sample testing on walls',
          'Final color approval',
          'Complete color palette',
          'Paint quantity estimation',
        ],
      },
    ],
  },
  {
    id: 'waterproofing',
    title: 'Waterproofing Services',
    services: [
      {
        title: 'Terrace Waterproofing',
        description: 'Complete terrace and roof waterproofing solutions to prevent leakage and seepage. We use advanced materials for long-lasting protection against monsoon and water damage.',
        image: 'https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?w=600&q=80',
        checklist: [
          'Leakage point detection',
          'Surface cleaning',
          'Crack sealing',
          'Waterproof membrane',
          'Chemical treatment',
          'Heat-reflective coating',
          'Drainage check',
          'Multiple layer protection',
          '5-year warranty',
        ],
      },
      {
        title: 'Bathroom Waterproofing',
        description: 'Specialized bathroom waterproofing to prevent seepage and water damage. Our solutions protect your walls and floors from moisture, mold, and structural damage.',
        image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&q=80',
        checklist: [
          'Seepage inspection',
          'Old tile/paint removal',
          'Joint sealing',
          'Waterproof coating',
          'Floor-wall junction seal',
          'Pipe penetration sealing',
          'Anti-fungal treatment',
          'Drainage inspection',
          'Quality guarantee',
        ],
      },
      {
        title: 'External Wall Waterproofing',
        description: 'Protect your exterior walls from rain, moisture, and dampness with our waterproofing solutions. Essential for properties exposed to heavy rainfall and humidity.',
        image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&q=80',
        checklist: [
          'Wall dampness check',
          'Crack identification',
          'Surface preparation',
          'Waterproof primer',
          'Elastomeric coating',
          'Window sill sealing',
          'Parapet treatment',
          'Weather-resistant finish',
          'Long-term protection',
        ],
      },
    ],
  },
];

// Common features for all services
export const serviceFeatures = [
  {
    title: 'Skilled Workforce',
    description: '50+ trained and experienced painters',
    icon: 'users',
  },
  {
    title: 'Premium Materials',
    description: 'Asian Paints & top brand products only',
    icon: 'award',
  },
  {
    title: 'On-Time Delivery',
    description: 'We complete projects as promised',
    icon: 'clock',
  },
  {
    title: 'Quality Guarantee',
    description: 'Satisfaction assured with warranty',
    icon: 'shield',
  },
  {
    title: 'Free Estimation',
    description: 'No-obligation quotes for all projects',
    icon: 'file-text',
  },
  {
    title: 'Clean Worksite',
    description: 'We leave your space spotless',
    icon: 'sparkles',
  },
];
